# 原有节点导入
from .batch_image_cropper import NODE_CLASS_MAPPINGS as CROPPER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROPPER_DISPLAY
from .zoey_tool import NODE_CLASS_MAPPINGS as ZOEY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ZOEY_DISPLAY
from .multifunctional_image_editor import NODE_CLASS_MAPPINGS as EDITOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EDITOR_DISPLAY
from .image_edit_prompt_generator import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY

# 新增：VR 360° 预览节点导入
try:
    from .vr_360_preview import NODE_CLASS_MAPPINGS as VR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VR_DISPLAY
except ImportError:
    VR_MAPPINGS = {}
    VR_DISPLAY = {}

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **CROPPER_MAPPINGS,
    **ZOEY_MAPPINGS,
    **EDITOR_MAPPINGS,
    **PROMPT_MAPPINGS,
    **VR_MAPPINGS  # ← 注入 VR 节点
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CROPPER_DISPLAY,
    **ZOEY_DISPLAY,
    **EDITOR_DISPLAY,
    **PROMPT_DISPLAY,
    **VR_DISPLAY  # ← 注入 VR 显示名
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
