# -*- coding: utf-8 -*-
"""MiniMax H3 · 双图参考版（Ref2VA）· 20 种风格整段提示词。

对应单图版 zoey_minimax_h3_styles.py 的 STYLE_MAP，但这里是「双图版」：
- <Picture 1> = 主体参考（保持真实外观、身份、整个真实环境场景全程不变，不作风格化）
- <Picture 2> = 风格化主体参考（保持外形/外观/色彩/身份不变，仅重渲染成对应艺术风格）

用途：给 MiniMax H3 参考转视频（Ref2VA）模式。图1主体与图2风格化主体全程互动，
一镜到底零切镜、不上墙（落到桌面/地板/手上）、暖萌收尾。
占位符：[MORPH]变形成什么  [ESCAPE_ROUTE]逃跑路线  [FINAL]最终形态/落点  [MOOD]情绪
"""

DUAL_STYLE_MAP = {
    "水墨 sumi-e": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：水墨水墨风格，流动墨迹/细笔触/淡墨晕染/宣纸肌理）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in sumi-e ink-wash style (flowing black ink, delicate brush strokes, soft ink bleed, graceful splashes, rice-paper texture). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in sumi-e ink-wash style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: quick brush strokes, ink wash, soft paper, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "赛博朋克 cyberpunk": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：赛博朋克霓虹风格，电光青与品红线条/色差光晕/网格反射/荧光拖痕）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in cyberpunk neon style (electric cyan & magenta lines, chromatic glow, grid reflections, luminous trace). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in cyberpunk neon style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: electric hum, synth blips, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "美漫 bold comic": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：美漫粗黑线风格，厚重黑描边/半调网点/鲜明平涂/动感速度线）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in bold American comic style (heavy black outlines, halftone dots, punchy flat colors, kinetic action lines). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in bold American comic style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: ink press, paper, pop, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "日漫 anime": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：清新日漫风格，纤细线稿/赛璐璐平涂/柔和阴影/灵动眼睛）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in clean anime style (fine line art, cel flat colors, soft shading, expressive eyes). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in clean anime style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: pencil, ink pen, cell loop, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "圆珠笔涂鸦 ballpoint doodle": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：圆珠笔涂鸦风格，细碎连续单色蓝线/紧张不均笔压/小墨点与停顿/笔记本质感/随性可爱/未打磨硬边线不填色）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in naive ballpoint-doodle style (thin continuous scratchy single-color blue pen lines, nervous uneven pressure, tiny ink blobs and hesitations, school-notebook feel, sketchy and playful, unpolished hard-edged linework with no fill). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in naive ballpoint-doodle style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: pen squeaks, scribble, rapid blots, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "黑白版画 linocut": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：黑白版画风格，印章式墨块/刻痕/高对比）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in bold linocut style (stamp-like black ink blocks, carve marks, high contrast). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in bold linocut style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: stamp, paper, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "石墨铅笔 graphite pencil": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：石墨铅笔风格，轻柔交叉排线/忧郁/精准）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in soft graphite-pencil style (gentle crosshatch, melancholic, precise). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in soft graphite-pencil style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: pencil, paper, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "纸片拼贴 paper collage": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：手工纸拼贴风格，平涂彩纸块/撕裂边缘/层叠剪贴）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in hand-cut paper-collage style (flat colored paper shapes, torn edges, layered cutout). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in hand-cut paper-collage style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: paper rustle, scissors, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "水彩 watercolor": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：松散水彩风格，透明晕染/柔和渗色/通透）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in loose watercolor style (translucent washes, soft color bleed, airy). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in loose watercolor style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: water, brush, paper, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "像素风 pixel": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：复古像素风格，粗糙像素块/有限色板/街机边缘）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in retro pixel-art style (chunky pixels, limited palette, arcade edges). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in retro pixel-art style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: 8-bit beeps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "油画 oil": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：油画风格，厚重堆叠笔触/丰富肌理/戏剧光影）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in painterly oil style (thick impasto strokes, rich texture, dramatic light). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in painterly oil style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: brush, canvas, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "蜡笔童趣 crayon": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：粗蜡笔风格，粗蜡笔画痕/不均颗粒/温馨童趣）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in chunky crayon style (thick waxy strokes, uneven specks, cozy playful). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in chunky crayon style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: crayon, paper, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "彩铅 Colored Pencil": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：柔和彩铅风格，蜡质叠色/轻柔铅笔笔触/素描本肌理）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in soft colored-pencil style (waxy layered shading, gentle pencil strokes, light sketchbook texture). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in soft colored-pencil style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: colored pencil, paper, soft taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "马克笔 Marker": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：鲜明马克笔风格，饱和平铺/干净手绘笔触/漫画粗糙感）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in bold vivid marker style (saturated flat fill, crisp hand-drawn strokes, comic rough). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in bold vivid marker style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: marker swipes, paper, quick taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "黏土 Claymation": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：定格黏土风格，圆润黏土形体/指纹肌理/手工感）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in stop-motion claymation style (soft rounded plasticine forms, fingerprint texture, handmade). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in stop-motion claymation style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: soft clay squish, thump, taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "折纸 Origami": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：折纸风格，锐利几何折痕/磨砂纸面）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in crisp folded-paper origami style (sharp geometric creases, matte paper facets). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in crisp folded-paper origami style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: paper crease, crisp fold, taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "玻璃彩绘 Stained Glass": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：彩色玻璃风格，半透明色块/深色铅条/发光）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in jewel-toned stained-glass style (translucent color panes, dark lead lines, glowing). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in jewel-toned stained-glass style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: glass chime, soft tink, taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "羊毛毡 Felt": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：羊毛毡风格，柔软蓬松纤维/温馨手作肌理）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in needle-felted wool style (soft fuzzy fibers, cozy handmade texture). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in needle-felted wool style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: soft felt rub, gentle taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "中国工笔 Gongbi": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：工笔画风格，细腻线稿/矿物颜料/典雅细节）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in fine gongbi brushwork style (delicate line art, muted mineral pigments, elegant detail). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in fine gongbi brushwork style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: delicate brush, rice paper, silk, taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),

    "波普 Pop Art": (
        "<Picture 1> 是主体参考（保持参考图1里这个主体的真实外观、身份以及整个真实环境场景全程不变，不作任何风格化，人物就保人物、物体就保物体）。\n"
        "<Picture 2> 是风格化主体参考（保持参考图2里这个主体的外形、外观，色彩与身份与上传时一致——仅将其艺术渲染风格改为：波普漫画风格，饱和三原色/半调网点/平涂海报色）。它始终保持同一个主体，绝不会变成另一种动物、绝不凭空生出非参考里的东西。\n"
        "[Shot 1] Live-action, one continuous take, FAST-PACED, playful (0–15s, no cuts). The real photographic subject in <Picture 1> keeps its exact identity, appearance, and the whole real scene unchanged and never stylized. The subject in <Picture 2> — whatever it is, as uploaded — keeps its EXACT same form, outline and identity (same species/breed/color/markings/pose as reference), but is re-rendered throughout in bold pop-art comic style (saturated primaries, halftone dots, flat poster colors). The <Picture 1> subject and the stylized <Picture 2> subject interact throughout: 0-3s they touch — the stylized subject lands, is nudged, dodges, nudges back; 3-6s they tease — it bounces, the <Picture 1> subject reaches or chases, it slips away then leaps up onto its shoulder and balances there; 6-10s it morphs into [MORPH] while racing, still in bold pop-art comic style, never the real <Picture 1> subject; 10-13s it escapes fast along [ESCAPE_ROUTE], camera drifting to keep both in frame; 13-15s it drifts back, stays low and near the subject, and settles into [FINAL] only on the tabletop, floor, or the subject's hands — never on any wall — warm and cute in [MOOD] with a playful joke. <Picture 1> subject and the whole scene stay real and unchanged: no 3D CGI, no smooth vector lines, no neon, no plush look, no horror/gore/big eyes/teeth, no jump scare, no black screen, no threat, no subtitles/logos/watermark, no motion smear, no flowing streak, nothing on walls.\n\n"
        "overall_soundscape: pop, comic ink, paper, taps, rapid taps, footsteps, fabric, room ambience, one soft playful pop.\n"
        "non_diegetic_music: N/A"
    ),
}
